### ISSUE TITLE
No Leancloud Application was linked to the project

### ISSUE THREAD

**Issue by ACCoder** [leancloud/python-getting-started#13]
本地运行出现这个
No Leancloud Application was linked to the project

**Comment by sdjcw** [comment]
你好，猜测是本地调试时 url 输入错误。
应该是： http://localhost:3000
而不是： http://<自定义二级域名>.leanapp.cn

因为后者是需要部署到服务端之后才可以。

**Comment by rickyfunfun** [comment]
应该说的不是这个问题。
如果用 python3.x 版本按照 readme 配置项目之后，运行./start.sh 是无法运行项目的。python3 app.py 也不行。用 lean up 跑起来项目，会出现  No Leancloud Application was linked to the project 这个提示。

**Comment by rickyfunfun** [comment]
知道问题了，是 readme 里面没有写完整。需要指定端口，然后运行 python3 wsgi.py
