### ISSUE TITLE
请问run_with_reloader如何添加对静态文件的改动监控

### ISSUE THREAD

**Issue by BadReese** [leancloud/python-getting-started#21]
每次HTML变更都要手动重启 很烦

**Comment by aisk** [comment]
是指模版文件吗？我刚才试了一下，模版文件和静态文件的改动虽然不会让服务重启，但是每次请求的时候都是会从磁盘重新读这个文件的。

有没有可能漏掉了[这句](https://github.com/leancloud/python-getting-started/blob/master/wsgi.py#L38)？这样会导致模版文件缓存。

**Comment by BadReese** [comment]
对，因为我是从其他地方引入的app,在wsgi里已经是被engine wrap后了，所以我调用的变成application.debug = True，这样是错的，应该在引入app的地方调用app.debug
谢谢~
