### ISSUE TITLE
云引擎对定时任务执行有问题

### ISSUE THREAD

**Issue by CoXier** [leancloud/python-getting-started#22]
你好，

我在云引擎中，新建了一个线程，然后让线程每隔5分钟去执行一个类似爬虫的操作，但是 LeanCloud 并不支持。我的代码如下：

```python
# wsgi.py
schedule.every(5).minutes.do(patrol.job)
t = Thread(target=patrol.run_schedule)
t.daemon = True
t.start()
```
因为本地debug时，不把线程的 `daemon` 设置成 `true` 会导致主程序停止后该子线程仍运行。

* **如果我把时间间隔改成 1 分钟那么是正常的**。
* 上面的代码在本地 debug 时运行正常

**Comment by CoXier** [comment]
突然发现时间间隔只要一长就有问题，和是否是 `daemon` 无关。

**Comment by aisk** [comment]
应该应用运行半个小时之后，没有收到外部请求，导致被休眠了。

**Comment by CoXier** [comment]
休眠是指整个机器停止运行了吗？
