### ISSUE TITLE
无法启动应用？

### ISSUE THREAD

**Issue by zhangxiliang** [leancloud/python-getting-started#23]
调用  python wsgi.py  启动报错如下

Traceback (most recent call last):
  File "wsgi.py", line 13, in <module>
    APP_ID = os.environ['r8OPq3qqsq6ygIhL8ORTvKd3-gzGzoHsz']
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'r8OPq3qqsq6ygIhL8ORTvKd3-gzGzoHsz'

**Comment by sdjcw** [comment]
获取 appId 的方式错了，应该是： `APP_ID = os.environ['LEANCLOUD_APP_ID']`

**Comment by zhangxiliang** [comment]
@sdjcw 一样的 ，不改成自己的APP_ID 一样报这个错

**Comment by sdjcw** [comment]
请问是怎样运行这个应用的？只有使用我们的云端云引擎或者本地使用我们提供的命令行工具来启动，这样运行环境才有 `LEANCLOUD_APP_ID` 的环境变量。

**Comment by zhangxiliang** [comment]
重新初始化一个项目，就可以了
